version: "3.6"
services:
 wordpress:
   image: wordpress:latest
   container_name: wordpress
   volumes:
     - ./wordpress:/var/www/html
   environment:
     - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
     - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
     - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
     - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
     - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
   depends_on:
     - db
     - phpmyadmin
   restart: always
   ports:
     - 8080:80
 
 db:
   image: mariadb:latest
   container_name: db
   volumes:
     - db_data:/var/lib/mysql
   environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - MYSQL_DATABASE=${MYSQL_DATABASE}
   restart: always
 
 phpmyadmin:
   depends_on:
     - db
   image: phpmyadmin/phpmyadmin:latest
   container_name: phpmyadmin
   restart: always
   ports:
     - 8180:80
   environment:
     PMA_HOST: ${PMA_HOST}
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
 
volumes:
 db_data: